SEED: 76
OUTPUT_DIR: /sharedata/home/daihzh/protein/ESM4SL/esm4sl/output/esm2/attn/test0

DATALOADER:
  BATCH_SIZE: 16
  NUM_WORKERS: 8
  PIN_MEMORY: False
  DROP_LAST: False
  PERSISTENT_WORKERS: False

DATASET:
  NAME: SLembDataset
  SL_ROOT: /sharedata/home/daihzh/protein/ESM4SL/data/cell-line_tables
  CELL_LINE: A549
  TEST_FOLD: 3  # generally shouldn't be None, and MUST be in {0, 1, ..., cv_num}
  NP_RATIO: 5  # 1, 5, 20, None

  ESM_ROOT: /sharedata/home/daihzh/protein/ESM4SL/data/ESM2_emb  # only if dataset is emb
  GENE_SEQ_PATH: null  # only if dataset is raw
  IF_RAW_SEQ: False

  TRANSFORM:
    NAME: null

MODEL:
  NAME: MultiLayerCrossAttention
  DEVICE: cuda

  IN_CHANNELS: 2560
  HIDDEN_CHANNELS: null
  OUT_CHANNELS: 1
  ACT_LAYER: gelu  # relu
  NORM_LAYER: batchnorm  # layernorm?
  EMBED_DIM: 96
  NUM_HEADS: 4
  NUM_LAYERS: 3

  ENCODER_WEIGHT: ""
  DECODER_WEIGHT: ""

  CRITERION:
    NAME: null
    TYPE: null

MODULE:
  NAME: ClsModule
  COMPILE: False

  OPTIMIZER:
    NAME: adamw
    BASE_LR: 0.001
    MOMENTUM: 0
    WEIGHT_DECAY: 0.01

  SCHEDULER:
    NAME: null  # LinearWarmupLR
    STEP_ON_EPOCHS: False

    MILESTONES: [110, 160]
    GAMMA: 0.1
    WARMUP_FACTOR: 0.1
    WARMUP_EPOCHS: 20
    FACTOR: 0.1
    PATIENCE: 10

TRAINER:
  STRATEGY: auto        # Set to `auto`, `ddp`, `deepspeed_stage_2`, `deepspeed_stage_3` ...
  MIXED_PRECISION: False

  CHECKPOINT:
    EVERY_N_EPOCHS: 5  # validate every n epochs
    SAVE_BEST: True    # If True, monitor will be required
    MONITOR: auprc

  MAX_EPOCHS: 100        # If profiler is enabled, this will be *automatically* set to 1
  LOG_EVERY_N_STEPS: 1
  ACCUMULATE_GRAD_BATCHES: 1

  CLIP_GRAD:
    ALGORITHM: null
    VALUE: null

  DETERMINISTIC: False  # Set to True to enable cudnn.deterministic
  BENCHMARK: False      # Set to True to enable cudnn.benchmark
  PROFILER: null        # Set to `advanced` or `pytorch` to enable profiling
  DETECT_ANOMALY: False # Set to True to enable anomaly detection
  SYNC_BATCHNORM: False # Set to True to enable sync batchnorm
